### PR TITLE
Add travic CI

### PR DESCRIPTION
**Pull request by FreeSlave**
Note: before merging, login to https://travis-ci.org/ and add your repo. This needs to be done because I provided a link to your user in travis badge (it won't work if you don't enable travis on phototonic yourself).

### CODE REVIEW

**Comment by FreeSlave** [comment]
@oferkv you've merged but it seems you forgot to add this repo to travis on your part. CI won't work if you don't enable it.

**Comment by oferkv** [comment]
Oops, OK added now.

**Comment by FreeSlave** [comment]
https://travis-ci.org/oferkv/phototonic still is not available. Maybe you should manually start the build or just add some commit (CI will should automatically).

**Comment by oferkv** [comment]
I triggered it on the site, seems OK, nice!

**Pull request merged**
