### PR TITLE
Updated German translation

### LINKED ISSUE #173: moving image "up" does not work
If I have an image zoomed beyond the size of the screen, I can move around in the image with the down, left and right keys, but up doesn't do anything.
What's strange is that in the default settings the "Nach oben" key is set to "alt+up", 
but alt+up also doesn't work.
The other keys "Nach unten", "Nach links" und "Nach rechts" are correctly set to "down","left" and "right".
Moving with the cursor keys inside the list view works as expected.

### PR DESCRIPTION
**Pull request by JHooverman**
Fixes #173
Interpreted "Up" as "Go to higher level directory" as suggested by @krzyc

### CODE REVIEW

**Comment by oferkv** [comment]
Hey Jonathan;
There seem to be some sort of conflict with this merge because I just merged a different fix by krzyc.
I think you need to pull again and then merge your fix.
Thanks!

**Comment by JHooverman** [comment]
Does it work now?

**Comment by oferkv** [comment]
Seems good, but one conflict still exists: only one of these should be left:

+<<<<<<< HEAD
+ <translation>Ausgewählt %1 von %2</translation>
+=======
<translation>Ausgewählt %1 von%2</translation>
<translation>Ausgewählt %1 von%2</translation>
+>>>>>>> upstream/master

**Comment by krzyc** [comment]
It probably will merge, but it contains diff commands:
+<<<<<<< HEAD
+ <translation>Ausgewählt %1 von %2</translation>
+=======
<translation>Ausgewählt %1 von%2</translation>
+>>>>>>> upstream/master

Above lines should be replaced by:
<translation>Ausgewählt %1 von%2</translation>

**Comment by JHooverman** [comment]
So, hopefully that's it :-)

**Comment by oferkv** [comment]
Thanks.

**Pull request merged**
